version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: policy-analyzer
    ports:
      - "8001:8000"
    env_file:
      - server/.env
    environment:
      - FIRECRAWL_SEARCH_ONLY=true
    restart: unless-stopped


